# Generated by Django 3.1.4 on 2021-01-04 01:34

from django.db import migrations, models

import apps.course.models.course


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="Title"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.course.models.course.image_course_upload_url,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="Slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Used for disabling the Course.",
                        verbose_name="active status",
                    ),
                ),
            ],
        ),
    ]
