# Generated by Django 3.1.4 on 2021-01-04 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"get_latest_by": "created", "ordering": ["-created", "-modified"]},
        ),
        migrations.AddField(
            model_name="course",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date time on which the object was created.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date time on which the object was last modified.",
                verbose_name="modified by",
            ),
        ),
    ]
